version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: /venv/bin/python server.py
    
